name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        description: Name of the artifact to download
        required: false
        default: dist
        type: string
    outputs:
      result: ${{ jobs.deploy.outputs.outcome }}
#    secrets:
#      secret-name:
#        description: Name of the secret to use
#        required: true
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: List contents
        run: ls
      - name: Output Information
        run: echo "Deploying to production"
      - name: Set output
        id: step-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT
